[tools]
nodejs = "22"

# Go
go = "1.24"

# Kubernetes
helm = "latest"
kubeconform = "latest"
"lima" = "2"

# misc
fd = "latest"
yq = "latest"

[settings]
experimental = true
task.disable_spec_from_run_scripts = true
raw = true

[hooks]
postinstall = ["{{ mise_bin }} setup"]

[task_config]
includes = [
    "./tasks.toml",
    "packages/ui/tasks.toml",
    "packages/controller/tasks.toml",
    "packages/api-server/tasks.toml",
    "packages/agent-runtime/tasks.toml",
    "deploy/helm/tasks.toml",
    "deploy/tasks.toml",
]
