// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.19.1
// source: external_auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";

export const protobufPackage = "envoy.service.auth.v3";

export interface CheckRequest {
  attributes: AttributeContext | undefined;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

export interface AttributeContext {
  source: Peer | undefined;
  destination: Peer | undefined;
  request: Request | undefined;
  tlsSession: TLSSession | undefined;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

export interface Peer {
  address: Address | undefined;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

export interface Address {
  socketAddress: SocketAddress | undefined;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

export interface SocketAddress {
  address: string;
  portValue: number;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

export interface Request {
  http: HttpRequest | undefined;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

/**
 * Populated for L7 ext_authz on the credentialed-egress chains; empty on the
 * L4 (network) ext_authz path.
 */
export interface HttpRequest {
  method: string;
  headers: { [key: string]: string };
  path: string;
  host: string;
  scheme: string;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

export interface HttpRequest_HeadersEntry {
  key: string;
  value: string;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

/**
 * Populated for L4 ext_authz when the listener has a TLS inspector — that's
 * where the SNI we gate on comes from.
 */
export interface TLSSession {
  sni: string;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

/** Standard google.rpc.Status — we only ever set `code`. */
export interface Status {
  code: number;
  message: string;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

export interface CheckResponse {
  /**
   * OkHttpResponse / DeniedHttpResponse fields exist upstream; we rely on
   * status.code = 0 → OK, anything else → PERMISSION_DENIED, which Envoy
   * honors regardless of whether the http details are populated.
   */
  status: Status | undefined;
  _unknownFields?: { [key: number]: Uint8Array[] } | undefined;
}

function createBaseCheckRequest(): CheckRequest {
  return { attributes: undefined, _unknownFields: {} };
}

export const CheckRequest: MessageFns<CheckRequest> = {
  encode(message: CheckRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attributes !== undefined) {
      AttributeContext.encode(message.attributes, writer.uint32(10).fork()).join();
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attributes = AttributeContext.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<CheckRequest>): CheckRequest {
    return CheckRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CheckRequest>): CheckRequest {
    const message = createBaseCheckRequest();
    message.attributes = (object.attributes !== undefined && object.attributes !== null)
      ? AttributeContext.fromPartial(object.attributes)
      : undefined;
    return message;
  },
};

function createBaseAttributeContext(): AttributeContext {
  return { source: undefined, destination: undefined, request: undefined, tlsSession: undefined, _unknownFields: {} };
}

export const AttributeContext: MessageFns<AttributeContext> = {
  encode(message: AttributeContext, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source !== undefined) {
      Peer.encode(message.source, writer.uint32(10).fork()).join();
    }
    if (message.destination !== undefined) {
      Peer.encode(message.destination, writer.uint32(18).fork()).join();
    }
    if (message.request !== undefined) {
      Request.encode(message.request, writer.uint32(34).fork()).join();
    }
    if (message.tlsSession !== undefined) {
      TLSSession.encode(message.tlsSession, writer.uint32(98).fork()).join();
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AttributeContext {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttributeContext();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.source = Peer.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.destination = Peer.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.request = Request.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.tlsSession = TLSSession.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<AttributeContext>): AttributeContext {
    return AttributeContext.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AttributeContext>): AttributeContext {
    const message = createBaseAttributeContext();
    message.source = (object.source !== undefined && object.source !== null)
      ? Peer.fromPartial(object.source)
      : undefined;
    message.destination = (object.destination !== undefined && object.destination !== null)
      ? Peer.fromPartial(object.destination)
      : undefined;
    message.request = (object.request !== undefined && object.request !== null)
      ? Request.fromPartial(object.request)
      : undefined;
    message.tlsSession = (object.tlsSession !== undefined && object.tlsSession !== null)
      ? TLSSession.fromPartial(object.tlsSession)
      : undefined;
    return message;
  },
};

function createBasePeer(): Peer {
  return { address: undefined, _unknownFields: {} };
}

export const Peer: MessageFns<Peer> = {
  encode(message: Peer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(10).fork()).join();
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Peer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<Peer>): Peer {
    return Peer.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Peer>): Peer {
    const message = createBasePeer();
    message.address = (object.address !== undefined && object.address !== null)
      ? Address.fromPartial(object.address)
      : undefined;
    return message;
  },
};

function createBaseAddress(): Address {
  return { socketAddress: undefined, _unknownFields: {} };
}

export const Address: MessageFns<Address> = {
  encode(message: Address, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.socketAddress !== undefined) {
      SocketAddress.encode(message.socketAddress, writer.uint32(10).fork()).join();
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Address {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.socketAddress = SocketAddress.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<Address>): Address {
    return Address.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Address>): Address {
    const message = createBaseAddress();
    message.socketAddress = (object.socketAddress !== undefined && object.socketAddress !== null)
      ? SocketAddress.fromPartial(object.socketAddress)
      : undefined;
    return message;
  },
};

function createBaseSocketAddress(): SocketAddress {
  return { address: "", portValue: 0, _unknownFields: {} };
}

export const SocketAddress: MessageFns<SocketAddress> = {
  encode(message: SocketAddress, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(18).string(message.address);
    }
    if (message.portValue !== 0) {
      writer.uint32(24).uint32(message.portValue);
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SocketAddress {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSocketAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.portValue = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<SocketAddress>): SocketAddress {
    return SocketAddress.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SocketAddress>): SocketAddress {
    const message = createBaseSocketAddress();
    message.address = object.address ?? "";
    message.portValue = object.portValue ?? 0;
    return message;
  },
};

function createBaseRequest(): Request {
  return { http: undefined, _unknownFields: {} };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.http !== undefined) {
      HttpRequest.encode(message.http, writer.uint32(18).fork()).join();
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.http = HttpRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.http = (object.http !== undefined && object.http !== null)
      ? HttpRequest.fromPartial(object.http)
      : undefined;
    return message;
  },
};

function createBaseHttpRequest(): HttpRequest {
  return { method: "", headers: {}, path: "", host: "", scheme: "", _unknownFields: {} };
}

export const HttpRequest: MessageFns<HttpRequest> = {
  encode(message: HttpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.method !== "") {
      writer.uint32(18).string(message.method);
    }
    globalThis.Object.entries(message.headers).forEach(([key, value]: [string, string]) => {
      HttpRequest_HeadersEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    if (message.path !== "") {
      writer.uint32(34).string(message.path);
    }
    if (message.host !== "") {
      writer.uint32(42).string(message.host);
    }
    if (message.scheme !== "") {
      writer.uint32(58).string(message.scheme);
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HttpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHttpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = HttpRequest_HeadersEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.headers[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.host = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.scheme = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<HttpRequest>): HttpRequest {
    return HttpRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HttpRequest>): HttpRequest {
    const message = createBaseHttpRequest();
    message.method = object.method ?? "";
    message.headers = (globalThis.Object.entries(object.headers ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.path = object.path ?? "";
    message.host = object.host ?? "";
    message.scheme = object.scheme ?? "";
    return message;
  },
};

function createBaseHttpRequest_HeadersEntry(): HttpRequest_HeadersEntry {
  return { key: "", value: "", _unknownFields: {} };
}

export const HttpRequest_HeadersEntry: MessageFns<HttpRequest_HeadersEntry> = {
  encode(message: HttpRequest_HeadersEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HttpRequest_HeadersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHttpRequest_HeadersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<HttpRequest_HeadersEntry>): HttpRequest_HeadersEntry {
    return HttpRequest_HeadersEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HttpRequest_HeadersEntry>): HttpRequest_HeadersEntry {
    const message = createBaseHttpRequest_HeadersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseTLSSession(): TLSSession {
  return { sni: "", _unknownFields: {} };
}

export const TLSSession: MessageFns<TLSSession> = {
  encode(message: TLSSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sni !== "") {
      writer.uint32(10).string(message.sni);
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TLSSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTLSSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sni = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<TLSSession>): TLSSession {
    return TLSSession.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TLSSession>): TLSSession {
    const message = createBaseTLSSession();
    message.sni = object.sni ?? "";
    return message;
  },
};

function createBaseStatus(): Status {
  return { code: 0, message: "", _unknownFields: {} };
}

export const Status: MessageFns<Status> = {
  encode(message: Status, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Status {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<Status>): Status {
    return Status.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Status>): Status {
    const message = createBaseStatus();
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseCheckResponse(): CheckResponse {
  return { status: undefined, _unknownFields: {} };
}

export const CheckResponse: MessageFns<CheckResponse> = {
  encode(message: CheckResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== undefined) {
      Status.encode(message.status, writer.uint32(10).fork()).join();
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of globalThis.Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = Status.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      const buf = reader.skip(tag & 7);

      const list = message._unknownFields![tag];

      if (list === undefined) {
        message._unknownFields![tag] = [buf];
      } else {
        list.push(buf);
      }
    }
    return message;
  },

  create(base?: DeepPartial<CheckResponse>): CheckResponse {
    return CheckResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CheckResponse>): CheckResponse {
    const message = createBaseCheckResponse();
    message.status = (object.status !== undefined && object.status !== null)
      ? Status.fromPartial(object.status)
      : undefined;
    return message;
  },
};

export type AuthorizationService = typeof AuthorizationService;
export const AuthorizationService = {
  check: {
    path: "/envoy.service.auth.v3.Authorization/Check" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckRequest): Buffer => Buffer.from(CheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckRequest => CheckRequest.decode(value),
    responseSerialize: (value: CheckResponse): Buffer => Buffer.from(CheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CheckResponse => CheckResponse.decode(value),
  },
} as const;

export interface AuthorizationServer extends UntypedServiceImplementation {
  check: handleUnaryCall<CheckRequest, CheckResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
