export {
  EXIT_SUCCESS as EXIT_AUTH_SUCCESS,
  EXIT_RUNTIME_FAILURE as EXIT_AUTH_RUNTIME_FAILURE,
  EXIT_INVALID_INPUT as EXIT_AUTH_INVALID_INPUT,
  EXIT_BELOW_FLOOR as EXIT_AUTH_BELOW_FLOOR,
} from "../../shared/exit-codes.js";

export const EXIT_AUTH_STATUS_NO_VALID = 4;
