export {
  EXIT_SUCCESS as EXIT_AGENT_SUCCESS,
  EXIT_RUNTIME_FAILURE as EXIT_AGENT_RUNTIME_FAILURE,
  EXIT_INVALID_INPUT as EXIT_AGENT_INVALID_INPUT,
  EXIT_BELOW_FLOOR as EXIT_AGENT_BELOW_FLOOR,
} from "../../shared/exit-codes.js";

export const EXIT_AGENT_NOT_RESOLVED = 5;
