export {
  EXIT_SUCCESS as EXIT_TEMPLATE_SUCCESS,
  EXIT_RUNTIME_FAILURE as EXIT_TEMPLATE_RUNTIME_FAILURE,
  EXIT_INVALID_INPUT as EXIT_TEMPLATE_INVALID_INPUT,
  EXIT_BELOW_FLOOR as EXIT_TEMPLATE_BELOW_FLOOR,
} from "../../shared/exit-codes.js";
