export {
  EXIT_SUCCESS as EXIT_INSTANCE_SUCCESS,
  EXIT_RUNTIME_FAILURE as EXIT_INSTANCE_RUNTIME_FAILURE,
  EXIT_INVALID_INPUT as EXIT_INSTANCE_INVALID_INPUT,
  EXIT_BELOW_FLOOR as EXIT_INSTANCE_BELOW_FLOOR,
} from "../../shared/exit-codes.js";

export const EXIT_INSTANCE_NOT_RESOLVED = 5;
