["controller:setup"]
dir = "{{config_root}}/packages/controller"
run = "go mod download"
sources = ["go.mod", "go.sum"]

["controller:check"]
depends = ["controller:check:*"]

["controller:check:vet"]
dir = "{{config_root}}/packages/controller"
run = "go vet ./..."
sources = ["**/*.go", "go.mod", "go.sum"]

["controller:check:build"]
dir = "{{config_root}}/packages/controller"
run = "go build -o dist/ ./..."
sources = ["**/*.go", "go.mod", "go.sum"]

["controller:fix"]
run = "echo 'No fix tasks for controller yet'"

["controller:test"]
dir = "{{config_root}}/packages/controller"
run = "go test ./..."

["controller:build"]
dir = "{{config_root}}/packages/controller"
run = "CGO_ENABLED=0 go build -o dist/controller ."
