name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        env:
          MISE_NODE_VERIFY: "false"
      - run: mise run setup
      - run: mise run check

  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      IS_SANDBOX: "1"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force

      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        env:
          MISE_NODE_VERIFY: "false"

      - name: Install dependencies
        run: mise run setup

      - name: Run e2e tests
        run: mise run api-server:e2e

      - name: Teardown test cluster
        if: always()
        run: mise run cluster:delete -- --force
